language: ruby
bundler_args: --without production

rvm:
  - 1.9.3
  - 2.0.0

gemfile:
  - gemfiles/activesupport_3.x.gemfile
  - gemfiles/activesupport_4.x.gemfile

notifications:
  webhooks:
    - https://idobata.io/hook/047eeb76-6f1f-4fc2-82f8-f8abceacd51e
